export default function onSiteLoad() {
console.clear();
console.log(`%c
Thanks for checking me out!
Say hello via LinkedIn or Email

• https://github.com/MisterPea
• https://www.linkedin.com/in/perry-angelora/
%c
..............................
..............___............. 
............./\\  \\............
............/::\\  \\........... 
.........../:/\\:\\__\\..........
........../:/ /:/  /..........
........./:/_/:/  /........... 
.........\\:\\/:/  /............
..........\\::/__/............. 
...........\\:\\  \\............. 
............\\:\\__\\............
.............\\/__/............
..............................
`, 'color:#d1c5ba; font-size: 12px;', 'color: #aca095; font-size: 12px; font-family: monospace, monospace-ui');
}


